config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :path_prefix => 'my'
  resources :users do 
    put :confirm, :on => :collection
    resources :skills
    resources :works
  end 

  root 'pages#index'

  get 'connections', to: 'users#index'

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :startups do 
    put :join, :on => :collection
    put :wishlist, :on => :collection
  end 
  resources :interests, only: [:destroy]
  get 'interests', to: 'interests#index'
  get 'startups', to: 'startups#index'

    resources :skills
    resources :works
    resources :conversations
    resources :personal_messages
end

app/models/work.rb
class Work < ApplicationRecord
    belongs_to :user
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = current_user.works.build
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = current_user.works.build(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to edit_user_path(current_user), notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_path(current_user.id), notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:company_name, :from, :to, :user_id)
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_form.html.erb
<%= simple_form_for([@user, @user.works.build]) do |f| %>
  <div class="form-inputs">
        <div><%= f.input :company_name, placeholder: 'Company Name' %></div>
        <div><%= f.input :from %></div>
        <div><%= f.input :to %></div>
      </div>
      <div class="form-actions">
          <%= f.submit "Add Work", class: 'btn btn-danger' %>
      </div>
<% end %>

app/views/works/_list.html.erb
<hr>
<table class="table table-hover table-bordered">
    <thead>
      <tr class="warning">
        <th>Company Name</th>
        <th>From</th>
        <th>To</th>
        <th>Option</th>
      </tr>
    </thead>
    <tbody>
  <% @works.each do |work| %>

             <tr>
        <td><%= work.company_name %></td>
        <td><%= work.from %></td>
        <td><%= work.to %></td>
        <td>
            <%= link_to work_path(work), method: :delete do %>
                <%= icon('trash') %>
            <% end %>
        </td>
      </tr>
   <% end %>

    </tbody>
  </table>

app/views/works/_works.html.erb
<%= render 'works/form' %>
<%= render "works/list" %>

app/views/works/edit.html.erb
<h1>Editing Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Works</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>From</th>
      <th>To</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @works.each do |work| %>
      <tr>
        <td><%= work.company_name %></td>
        <td><%= work.from %></td>
        <td><%= work.to %></td>
        <td><%= link_to 'Show', work %></td>
        <td><%= link_to 'Edit', edit_work_path(work) %></td>
        <td><%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Work', new_work_path %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form', work: @work %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @work.company_name %>
</p>

<p>
  <strong>From:</strong>
  <%= @work.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @work.to %>
</p>

<%= link_to 'Edit', edit_work_path(@work) %> |
<%= link_to 'Back', works_path %>