config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :path_prefix => 'my'
  resources :users do 
    put :confirm, :on => :collection
    resources :skills
    resources :works
  end 

  root 'pages#index'

  get 'connections', to: 'users#index'

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :startups do 
    put :join, :on => :collection
    put :wishlist, :on => :collection
  end 
  resources :interests, only: [:destroy]
  get 'interests', to: 'interests#index'
  get 'startups', to: 'startups#index'

    resources :skills
    resources :works
    resources :conversations
    resources :personal_messages
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "75x75>" }, :default_url => ActionController::Base.helpers.asset_path("missing.png")
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum:20}

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :startups, dependent: :destroy
  belongs_to :team
  has_many :interests, dependent: :destroy
  has_many :skills, dependent: :destroy
  has_many :works, dependent: :destroy
  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy



  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
    self.inverse_friendships.where(state: "pending")
  end

  def pending_friend_requests_to
    self.friendships.where(state: "pending")
  end

  def active_friends
    self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end

  def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id])
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end

  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id]).first
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :index]
	before_action :set_user, only:[:show]
  before_action :get_counts, only: [:index]

	def index
		case params[:people] when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
      @users = current_user.pending_friend_requests_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end
	end

  def show
      @activities = PublicActivity::Activity.where(owner_id: @user.id)
      @startups = @user.startups.all.order("created_at DESC")
      @joinrequests = []
        current_user.startups.each do |startup|
          @joinrequests << startup.teams.where(status: "pending")
        end
  end

    def confirm 
        @request = Team.find_by(user_id: params[:id])
        @request.status = "confirmed"
        if @request.save
            redirect_to root_path, notice: "You Accepted new member in your team"
        end 
    end 

   
  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
          @skills = current_user.skills.all
          @works = current_user.works.all
  end

  # POST /users
  # POST /users.json
  def create
      @user = User.new(user_params)
      if @user.save
         redirect_to root_path, :notice => 'User was successfully created.' 
      else
        render 'new'
      end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to edit_user_path(@user), :notice => " #{@user.fullname} details was successfully updated. " 
      else
       render 'edit'
      end
  end

  private

  def get_counts
    @friend_count = current_user.active_friends.size
    @pending_count = current_user.pending_friend_requests_to.map(&:friend).size
  end

  def set_user
  	@user = User.find_by(username: params[:id])
  end

  def user_params 
    	params.require(:user).permit(:email, :password, :password_confirmation, :username, :bio, :age,
		 :gender, :avatar, :fullname, :designation)
  end 
  
end

app/helpers/users_helper.rb
module UsersHelper
	def action_buttons(user)
		case current_user.friendship_status(user) when "friends"
			link_to "Terminate Connection", friendship_path(current_user.friendship_relation(user)), method: :delete, class: "btn btn-xs btn-danger"
		when "pending"
			link_to "Terminate Request", friendship_path(current_user.friendship_relation(user)), method: :delete, class: "btn btn-xs btn-warning"
		when "requested"
			link_to "Accept Connection", accept_friendship_path(current_user.friendship_relation(user)), method: :put, class: "btn btn-xs btn-success"
		when "not_friends"
			link_to "Connect", friendships_path(user_id: user.id), method: :post, class: "btn btn-xs btn-primary"
		end
	end
end

app/views/users/_general.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
  <br>
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fullname, required: false %>
    <%= f.input :designation, required: false %>
    <%= f.input :age %>
    <%= f.select(:gender, ['Male','Female'], {}, { :class => 'form-control' }) %>
    <hr>
    <%= f.input :bio %>
  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit, "Save Information", class: 'btn btn-danger' %>
  </div>
<% end %>
<!--- End General -->
</div>
  </div>
</div>

app/views/users/_password.html.erb
     <div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
  <br>
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :password, autocomplete: "off", hint: "leave it blank if you don't want to change it", required: false %>
    <%= f.input :password_confirmation, required: false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update Password", class: 'btn btn-danger' %>
  </div>
<% end %>
<br>
    </div></div></div>

app/views/users/_settings.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
  <br>
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username, required: false %>
    <%= f.input :email %>
    <hr>
    <%= f.input :avatar, as: :file, label: 'Personal Image', class: 'form-control' %>
<hr>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update Settings", class: 'btn btn-danger' %>
  </div>
<% end %>
<br>
    </div></div></div>

app/views/users/_user.html.erb
<div class="col-md-3">
<div class="thumbnail"><br>
<%= link_to user_path(user.username) do %>
	 <%= image_tag user.avatar.url(:thumb), class: 'avatar' %>
<% end %>
<div class="caption">
<h3><%= user.fullname %></h3>
<p>@<%= user.username %></p>
<% if current_user %>
<p><%= action_buttons(user)%></p>
<% end %>
</div>
</div>
</div>

app/views/users/edit.html.erb
<div class="well">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">General Information</a></li>
    <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Profile Configurations</a></li>
    <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">Skills & Experience</a></li>
    <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Change Password</a></li>
  </ul>

  <!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="home">
      <%= render 'general' %>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="profile">
    <%= render 'settings' %>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="messages">
    <div class="container">
      <div class="row">
        <br>
        <div class="col-md-4 col-md-offset-1">
          <h4>Your Skills</h4>
          <hr>
          <%= render 'skills/skills' %>
          </div>
        <div class="col-md-4 col-md-offset-1">
          <h4>Work History</h4>
          <hr>
          <%= render 'works/works' %>
          </div>
      </div>
    </div>
    

  </div>
  <div role="tabpanel" class="tab-pane fade" id="settings">
    <%= render 'password' %>
  </div>
</div>
</div>

app/views/users/index.html.erb
<div class="jumbotron text-center">
<h2>Connections</h2>
<div class="btn-group" role="group" aria-label="Default Button Groups">
<%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
<%= link_to "Friends", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
<%= link_to "Requests", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
<%= link_to "Pending", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
</div>
</div>

<div class="container">
<div class="row">
<%= render @users %>
</div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
    <%= f.input :password_confirmation %>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-8">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                             <div class="media">
                                <div class="media-left">
                                     <%= image_tag @user.avatar.url(:thumb), class: 'avatar' %>
                                </div>
                                <div class="media-body">
                                     <h4 class="media-heading user-full-name"> <%= @user.fullname %> </h4>
                                      <p class="user-designation"><%= @user.designation %> </p>
                                     <span class="user-profile-details">Age : <%= @user.age%> Gender : <%= @user.gender %></span>
                                     <% if current_user.id != @user.id %>
                                     <p class="user-profile-details">
                                     <%= link_to  new_personal_message_path(receiver_id: @user.id) do %>
                                        <%= icon('comment', 'Send Message') %>
                                     <% end %>
                                     </p>
                                     <% end %>
                                </div>
                             </div>
                        </div>
                        
                        <div class="panel-body">
                             <%= @user.bio %>
                             <hr>
                             <h4><%= @user.fullname %> Skills</h4>
                             <ol>
                               <% @user.skills.each do |skill| %>
                                 <li><p><%= skill.title %>, <%= skill.exp %> Years </p></li>
                                <% end %>
                             </ol>
                             <hr>
                             <h4><%= @user.fullname %> Work History</h4>
                             <ol>
                               <% @user.works.each do |work| %>
                                 <li><p><%= work.company_name %>, <span class="specific-date">From : <%= work.from %>, To : <%= work.to %></span></p></li>
                                <% end %>
                             </ol>
            
                                
                             

                        </div>

                        <div class="panel-footer">                         
                            <ul class="startup-ul">
                            <% @startups.each do |s| %>
                                <li>
                                <%= link_to startup_path(s) do %>
	 			                    <%= image_tag s.logo.url(:thumb), class: 'founded-startup-logo', 'data-toggle': 'tooltip', 'data-placement':'top' ,title: "Founder of : " +s.name %>
			                    <% end %>
                                </li>
                            <% end %>
                            </ul>
                    
                        </div>
                    </div>
        </div>
        <div class="col-md-4">
		    <div class="panel panel-default">
		            <div class="panel-heading">Recent Activity</div>
		            <div class="panel-body">
		                	<%= render_activities(@activities) %>
		            </div>
		    </div>

            <% if current_user.id == @user.id  %>
            <div class="panel panel-default">
		            <div class="panel-heading">Pending Startup Joining Request</div>
		            <div class="panel-body">
		                	<% @joinrequests.each do |request| %>
                                <% request.each do |r| %>
                                    <% r.users.each do |m| %>
                                        <span class="label label-default"><%= r.status %></span> <%= m.fullname %>
                                        <%= link_to "confirm", {:controller => :users, :action => :confirm, :id => m.id}, :method => :put  %>
                                     <hr>
                                    <% end %>
                                <% end %>
                            <% end %>
		            </div>
		    </div>
            <% end %>

        </div>
    </div>
</div>

<script>
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>