config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :path_prefix => 'my'
  resources :users do 
    put :confirm, :on => :collection
    resources :skills
    resources :works
  end 

  root 'pages#index'

  get 'connections', to: 'users#index'

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :startups do 
    put :join, :on => :collection
    put :wishlist, :on => :collection
  end 
  resources :interests, only: [:destroy]
  get 'interests', to: 'interests#index'
  get 'startups', to: 'startups#index'

    resources :skills
    resources :works
    resources :conversations
    resources :personal_messages
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]

  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = current_user.skills.build
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = current_user.skills.build(skill_params)
      if @skill.save
        redirect_to edit_user_path(current_user), notice: 'Skills Updated'
      else
        render 'new'
      end
  end

  # PATCH/PUT /skills/1
  # PATCH/PUT /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_path(current_user.id), notice: 'Skill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def skill_params
      params.require(:skill).permit(:title, :exp, :user_id)
    end
    
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= simple_form_for([@user, @user.skills.build]) do |f| %>
  <div class="form-inputs">
        <div><%= f.input :title, placeholder: 'Skill Title' %></div>
        <div><%= f.input :exp, placeholder: '0' %></div>
      </div>
      <div class="form-actions">
          <%= f.submit "Add Skill", class: 'btn btn-danger' %>
      </div>
<% end %>

app/views/skills/_list.html.erb
<hr>
<table class="table table-hover table-bordered">
    <thead>
      <tr class="warning">
        <th>Skill</th>
        <th>Experience</th>
        <th>Option</th>
      </tr>
    </thead>
    <tbody>
  <% @skills.each do |skill| %>

             <tr>
        <td><%= skill.title %></td>
        <td><%= skill.exp %> Years</td>
        <td>
            <%= link_to skill_path(skill), method: :delete do %>
                <%= icon('trash') %>
            <% end %>
        </td>
      </tr>
   <% end %>

    </tbody>
  </table>

app/views/skills/_skills.html.erb
<%= render 'skills/form' %>
<%= render "skills/list" %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skills</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Exp</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <td><%= skill.title %></td>
        <td><%= skill.exp %></td>
        <td><%= skill.user %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @skill.title %>
</p>

<p>
  <strong>Exp:</strong>
  <%= @skill.exp %>
</p>

<p>
  <strong>User:</strong>
  <%= @skill.user %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>