config/routes.rb
Rails.application.routes.draw do

 devise_for :users, :path_prefix => 'my'
  resources :users do 
    put :confirm, :on => :collection
    resources :skills
    resources :works
  end 

  root 'pages#index'

  get 'connections', to: 'users#index'

  resources :friendships, only: [:create, :destroy, :accept] do 
    member do 
      put :accept
    end
  end

  resources :startups do 
    put :join, :on => :collection
    put :wishlist, :on => :collection
  end 
  resources :interests, only: [:destroy]
  get 'interests', to: 'interests#index'
  get 'startups', to: 'startups#index'

    resources :skills
    resources :works
    resources :conversations
    resources :personal_messages
end

app/views/layouts/_notregistered.html.erb
   <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
             <li>
              <%= link_to new_user_path do %>
                <%= icon('certificate', 'Join Us NOW') %>
              <% end %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to  new_user_session_path do %>
                <%= icon('sign-in','Login') %>
              <% end %>
            </li>
         </ul>
        </div><!-- /.navbar-collapse -->

app/views/layouts/_registered.html.erb
   <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
             <li>
              <%= link_to user_path(current_user.username) do %>
                <%= icon('user-circle', current_user.username) %>
              <% end %>
            </li>
             <li>
              <%= link_to connections_path do %>
                <%= icon('group', 'Connections') %>
              <% end %>
            </li>
             <li>
              <%= link_to startups_path do %>
                <%= icon('diamond', 'Startups') %>
              <% end %>
            </li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to  conversations_path do %>
                <%= icon('comments','Messages') %>
              <% end %>
            </li>
            <li>
              <%= link_to  interests_path do %>
                <%= icon('heart','Interest List') %>
              <% end %>
            </li>
              <li class="dropdown">
                <%= link_to  "#", class: 'dropdown-toggle', 'data-toggle': 'dropdown', 'aria-haspopup': 'true' do %>
                  <%= icon('cog', 'Settings') %>
                <% end %>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to edit_user_path(current_user.id) do  %>
                      <%= icon('list-alt', 'Edit Profile') %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to connections_path do %>
                      <%= icon('tasks', 'Manage Connections') %>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to new_startup_path do  %>
                      <%= icon('clone', 'Create Startup Profile') %>
                    <% end %>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                      <%= icon('sign-out', 'Logout') %>
                    <% end %>
                  </li>
                </ul>
              </li>
         </ul>
        </div><!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "Iostartups" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
    
    
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to  "IO Startups", root_path, class: 'navbar-brand' %>
        </div>

        <% if user_signed_in? %>
          <%= render 'layouts/registered' %>
        <% else %>
          <%= render 'layouts/notregistered' %>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    
    </div> <!-- /container -->

  </body>
</html>